name: krypton
version: 0.1.0
description: >-
  Client library to connect to a Krypton Authentification server.
homepage: https://github.com/krypton-org/krypton-flutter
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  graphql: ^3.0.0
dev_dependencies:
  test: ^1.6.0
