# Inspired from Dart CI
# See: https://github.com/actions/starter-workflows/blob/master/ci/dart.yml
# Copyright starter-workflows contributors - MIT License
 
name: Krypton Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Start MongoDB instance for testing purposes
      run: docker run --detach --name krypton-auth-db-test --network krypton-auth-net-test mongo
    - name: Start Krypton Auth middleware for testing purposes
      run: docker run --detach --name krypton-auth-test --network krypton-auth-net-test --env MONGODB_URI="mongodb://krypton-auth-db-test:27017/users" --publish 5000:5000 kryptonorg/krypton-auth
    - name: Run tests
      run: pub run test
    - name: Stop Krypton Auth middleware
      run: docker rm -f docker rm -f krypton-auth-test
    - name: Stop MongoDB instance
      run: docker rm -f krypton-auth-db-test
