# Inspired from Dart CI
# See: https://github.com/actions/starter-workflows/blob/master/ci/dart.yml
# Copyright starter-workflows contributors - MIT License
 
name: Krypton Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: ./tool/start-krypton-auth.sh 
      run: pub run test
    - name: Run tests
      run: pub run test
    - name: Cleanup
      run: ./tool/stop-krypton-auth.sh
